# Generated by Django 4.1.3 on 2022-11-04 23:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
                ('photo_src', models.CharField(max_length=100, unique=True)),
                ('buyer', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=100, unique=True)),
                ('wolt_link', models.CharField(max_length=100, unique=True)),
                ('dimensions', models.CharField(max_length=100, unique=True)),
                ('weight', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
