# Generated by Django 4.1.3 on 2022-11-05 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wolt_link',
        ),
        migrations.AlterField(
            model_name='item',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerProduct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('APPAREL', 'Apparel'), ('ELECTRONICS', 'Apparel'), ('GARDEN', 'Garden & Outdoors'), ('SUPPLIES', 'Supplies'), ('SPORT', 'Sporting goods'), ('HOME', 'Home goods'), ('GAMES', 'Toys and Games'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo_src',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('LISTED', 'Listed'), ('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered'), ('DELETED', 'Deleted')], default='LISTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProduct', to=settings.AUTH_USER_MODEL),
        ),
    ]
