# Generated by Django 4.1.3 on 2022-11-05 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_item_weight_remove_item_wolt_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_id',
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, related_name='productUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productBuyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
