# Generated by Django 4.1.3 on 2022-11-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_item_user_id_item_user_alter_item_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('ALMOST_NEW', 'Almost new'), ('USED', 'Used'), ('DAMAGED', 'Damaged')], default='USED', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('APPAREL', 'Apparel'), ('ELECTRONICS', 'Electronics'), ('GARDEN', 'Garden & Outdoors'), ('SUPPLIES', 'Supplies'), ('SPORT', 'Sporting goods'), ('HOME', 'Home goods'), ('GAMES', 'Toys and Games'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
