# Generated by Django 4.1.3 on 2022-11-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pickup_time_from',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pickup_time_to',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
