# Generated by Django 4.1.3 on 2022-11-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_pickup_time_from_item_pickup_time_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo_src',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/thumbnails/000/356/559/small_2x/10__2832_29.jpg', max_length=500),
        ),
    ]
